# Generated by Django 5.1 on 2024-08-21 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_caption', models.CharField(max_length=30)),
                ('design_rate', models.CharField(max_length=30)),
                ('design_file', models.FileField(upload_to='Assets/Designer/Designs/')),
                ('design_upload_date', models.DateField(auto_now_add=True)),
                ('design_description', models.CharField(max_length=100)),
                ('design_status', models.IntegerField(default=0)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer')),
            ],
        ),
    ]
