# Generated by Django 5.1 on 2024-08-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0001_initial'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designcopyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_date', models.DateField(auto_now_add=True)),
                ('copyright_status', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Designer.tbl_design')),
            ],
        ),
    ]
