# Generated by Django 5.1 on 2024-08-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0002_tbl_designcopyright'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_designcopyright',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_company'),
        ),
    ]
