# Generated by Django 5.1 on 2024-10-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0003_alter_tbl_designcopyright_company'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_content', models.CharField(max_length=200)),
                ('complaint_reply', models.CharField(max_length=200)),
                ('complaint_status', models.IntegerField(default=0)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer')),
            ],
        ),
    ]
