# Generated by Django 5.1 on 2024-08-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_designer',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_company',
        ),
        migrations.DeleteModel(
            name='tbl_designer',
        ),
    ]
