# Generated by Django 5.1 on 2024-08-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0002_remove_tbl_designer_place_delete_tbl_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_email', models.CharField(max_length=30)),
                ('company_contact', models.CharField(max_length=30)),
                ('company_password', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=50)),
                ('company_logo', models.FileField(upload_to='Assets/Company/Logo')),
                ('company_proof', models.FileField(upload_to='Assets/Company/proof')),
                ('company_doj', models.DateField(auto_now_add=True)),
                ('company_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=30)),
                ('designer_email', models.CharField(max_length=30)),
                ('designer_contact', models.CharField(max_length=30)),
                ('designer_password', models.CharField(max_length=30)),
                ('designer_address', models.CharField(max_length=50)),
                ('designer_photo', models.FileField(upload_to='Assets/Designer/Photo')),
                ('designer_proof', models.FileField(upload_to='Assets/Designer/Proof')),
                ('designer_doj', models.DateField(auto_now_add=True)),
                ('designer_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
